[tool.poetry]
name = "FastAPI API"
description = "API for URL shortener."
authors = ["kramber1024 <kramber268@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112"
uvicorn = { extras = ["standart"], version = "^0.30.1" }
pydantic = { extras = ["email"], version = "^2" }
pydantic-settings = "^2"
sqlalchemy = { extras = ["asyncio"], version = "^2.0.31" }
aiosqlite = "^0.20.0"
snowflake-id = "^1.0.2"
bcrypt = "^4.1.3"
pyjwt = { extras = ["crypto"], version = "^2.8.0" }

[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"
pytest-cov = "^5"
pytest-asyncio = "^0.24"
httpx = "^0.27"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6"
mypy = "^1.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
strict = true
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
exclude = [".git", ".mypy_cache", ".pytest_cache", ".venv", ".vscode"]


[tool.coverage.run]
omit = ["tests/*", "app/main.py"]
concurrency = ["greenlet", "thread"]

[tool.coverage.report]
exclude_lines = [
  "if TYPE_CHECKING:",
  "if __name__ == .__main__.:",
  "pragma: no cover",
]
